/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/backTop.vue')['default']
    Banner: typeof import('./src/components/banner.vue')['default']
    Cart: typeof import('./src/components/cart.vue')['default']
    FixedSearch: typeof import('./src/components/search/fixedSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/search.vue')['default']
    SlideGrid: typeof import('./src/components/slideGrid.vue')['default']
    StickyTabs: typeof import('./src/components/stickyTabs.vue')['default']
    Waterfall: typeof import('./src/components/waterfall.vue')['default']
  }
}
