/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/back-top.vue')['default']
    Banner: typeof import('./src/components/banner.vue')['default']
    Card: typeof import('./src/components/shop/card.vue')['default']
    Cart: typeof import('./src/components/cart.vue')['default']
    Check: typeof import('./src/components/shop/check.vue')['default']
    Declare: typeof import('./src/components/shop/declare.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    FixedSearch: typeof import('./src/components/search/fixed-search.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/search.vue')['default']
    SlideGrid: typeof import('./src/components/slide-grid.vue')['default']
    StatusBar: typeof import('./src/components/status-bar.vue')['default']
    StickyTabs: typeof import('./src/components/sticky-tabs.vue')['default']
    Waterfall: typeof import('./src/components/waterfall.vue')['default']
  }
}
