export {
	STORAGE_CONFIG,
	BANNER_DATA,
	GRID_DATA,
	TAB_DATA,
	GOODS_DATA,
	CLASSIFY_DATA,
	CART_GOODS_DATA,
	GOODS_BANNER_DATA,
	ORDER_GRID_DATA,
	FEATURE_GRID_DATA,
	FEATURE_GRID_DATA2,
	ADDRESS_DATA,
	ORDER_GOODS_DATA,
	AREA_DATA
} from "./data";